version: "3.9"

networks:
  algafood-network:
    driver: bridge
    
services:
  algafood-mysql:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: "abc121314"
    ports: 
      - "3316:3306"
    networks:
      - algafood-network
      
  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3316", "-t", "480", "--", "java", "-jar", "api.jar"]
    environment:  
      DB_HOST: algafood-mysql
    networks:
      - algafood-network
    depends_on: 
      - algafood-mysql
      
      